channel_contract_type_id_args = "0x4d63d2d59c9f8e2b117cde09bb3d705b82e0e21216a3cc54967e715bf19a25b8"
packet_contract_type_id_args = "0x7e2f534bf12a8f596411ca8c02f698b8cdc3581e851325b4fbb7580b1f20e289"
channel_id = 0
confirmations = 3

ckb_rpc_url = "https://testnet.ckbapp.dev/"

[module_lock_script]
code_hash = "0x12b7f23d284e3221fe0730ca5753c28f9302c7368d83101637684c424b242a95"
hash_type = "type"
args = "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"

[axon_metadata_type_script]
code_hash = "0x00000000000000000000000000000000000000000000000000545950455f4944"
hash_type = "type"
args = "0xb2cb0aafcf2bcf4095930621a7f82f411adec578fe83c4f15e32b8230aa3ec28"

[sudt_transfer_contract_type_script]
code_hash = "0x00000000000000000000000000000000000000000000000000545950455f4944"
hash_type = "type"
args = "0x9f3538c666de488c38a246e4c6e1f95a04d4dd250b7d5b6a26092b6f330e7215"

[sudt.yukun_li]
code_hash = "0xc5e5dcf215925f7ef4dfaf5f4b4f105bc321c02776d6e7d52a1db3fcd9d011a4"
hash_type = "type"
args = "0xc219351b150b900e50a7039f1e448b844110927e5fd9bd30425806cb8ddff1fd"
