# this is a deployment file for ckb testnet

[[cells]]
name = "ibc-sudt-transfer"
enable_type_id = true
location = { file = "../ibc-sudt-transfer" }

# The lock script set to output cells
[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0x470dcdc5e44064909650113a274b3b36aecb6dc7"
hash_type = "type"
