[package]
name = "forcerelay-test"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
ckb-sdk = "=2.4.0"
ckb-jsonrpc-types = "0.106.0"
ckb-types = "0.106.0"
hex = "0.4"

eth_light_client_in_ckb-verification = { version = "0.1.0-alpha.0", git = "https://github.com/synapseweb3/eth-light-client-in-ckb", rev = "e94ec1a" }
